package caverna;

public class Boss {

	private static final String DOMANDE[] = 
	    {
	        "QUAL È LA CAPITALE DELLA FRANCIA?",
	        "IN QUALE ANNO È FINITA LA SECONDA GUERRA MONDIALE?",
	        "CHI HA SCRITTO 'ROMEO E GIULIETTA'?",
	        "QUAL È IL PIANETA PIÙ GRANDE DEL NOSTRO SISTEMA SOLARE?",
	        "QUAL È L'ELEMENTO CON IL SIMBOLO CHIMICO 'H'?",
	        "QUAL È LA RADICE QUADRATA DI 64?",
	        "CHI È STATO IL PRIMO PRESIDENTE DEGLI STATI UNITI?",
	        "QUANTI CONTINENTI CI SONO NEL MONDO?",
	        "IN QUALE ANNO È STATA FONDATA L'ONU?",
	        "CHI È L'AUTORE DI 'DIVINA COMMEDIA'?",
	        "QUALE È IL FIUME PIÙ LUNGO DEL MONDO?",
	        "CHI È STATO IL PRIMO UOMO SULLA LUNA?",
	        "IN QUALE ANNO È INIZIATA LA PRIMA GUERRA MONDIALE?",
	        "CHI È IL PITTORE DI 'MONNA LISA'?",
	        "QUAL È IL PIÙ GRANDE OCEANO DEL MONDO?",
	        "CHI È L'AUTORE DI 'I PROMESSI SPOSI'?",
	        "IN QUALE ANNO È STATO FIRMATO IL TRATTATO DI ROMA?",
	        "QUAL È IL MONTE PIÙ ALTO DEL MONDO?",
	        "CHI È L'AUTORE DI 'IL PRINCIPE'?",
	        "QUAL È LA VALUTA DELL'ITALIA?",
	        "IN QUALE ANNO È AVVENUTA LA CADUTA DEL MURO DI BERLINO?",
	        "CHI È IL COMPOSITORE DI 'LE QUATTRO STAGIONI'?",
	        "QUAL È IL PIÙ GRANDE DESERTO DEL MONDO?",
	        "CHI È CONSIDERATO IL PADRE DELLA PSICOANALISI?",
	        "QUALE È IL LAGO PIÙ PROFONDO DEL MONDO?",
	        "IN QUALE ANNO È STATO FIRMATO IL TRATTATO DI VERSAILLES?",
	        "CHI È IL FONDATORE DI MICROSOFT?",
	        "QUAL È IL PIÙ GRANDE ANIMALE DEL MONDO?",
	        "QUAL È IL MIGLIOR GIOCATORE DI CALCIO DI SEMPRE?",
	        "QUAL È IL MIGLIOR GIOCATORE DI CALCIO DI SEMPRE?"
	    };

	private static final String RISPOSTE[] = 
	    {
	        "PARIGI", "BERLINO", "LONDRA", "MADRID",   // CORRETTA: PARIGI
	        "1903", "1939", "1945", "1960",   // CORRETTA: 1945
	        "WILLIAM SHAKESPEARE", "CHARLES DICKENS", "JANE AUSTEN", "DANTE ALIGHIERI",   // CORRETTA: WILLIAM SHAKESPEARE
	        "TERRA", "SATURNO", "GIOVE", "NETTUNO",   // CORRETTA: GIOVE
	        "AZOTO", "OSSIGENO", "IDROGENO", "CARBONIO",   // CORRETTA: IDROGENO
	        "6", "8", "10", "12",   // CORRETTA: 8
	        "GEORGE WASHINGTON", "THOMAS JEFFERSON", "JOHN ADAMS", "JAMES MADISON",   // CORRETTA: GEORGE WASHINGTON
	        "5", "6", "7", "8",   // CORRETTA: 7
	        "1969", "1950", "1948", "1945",   // CORRETTA: 1945
	        "DANTE ALIGHIERI", "PETRARCA", "BOCCACCIO", "ARIOSTO",   // CORRETTA: DANTE ALIGHIERI
	        "DANUBIO", "AMAZONAS", "MISSISSIPPI", "NILO",   // CORRETTA: NILO
	        "NEIL ARMSTRONG", "BUZZ ALDRIN", "YURI GAGARIN", "JOHN GLENN",   // CORRETTA: NEIL ARMSTRONG
	        "1918", "1920", "1914", "1939",   // CORRETTA: 1914
	        "LEONARDO DA VINCI", "MICHELANGELO", "RAFFAELLO", "CARAVAGGIO",   // CORRETTA: LEONARDO DA VINCI
	        "PACIFICO", "ATLANTICO", "INDIANO", "ANTARTICO",   // CORRETTA: PACIFICO
	        "ALESSANDRO MANZONI", "GIACOMO LEOPARDI", "LUIGI PIRANDELLO", "ITALO CALVINO",   // CORRETTA: ALESSANDRO MANZONI
	        "1957", "1951", "1955", "1958",   // CORRETTA: 1957
	        "K2", "MONTE BIANCO", "MONTE EVEREST", "KANGCHENJUNGA",   // CORRETTA: MONTE EVEREST
	        "NICCOLÒ MACHIAVELLI", "THOMAS HOBBES", "JOHN LOCKE", "JEAN-JACQUES ROUSSEAU",   // CORRETTA: NICCOLÒ MACHIAVELLI
	        "EURO", "LIRA", "DOLLARO", "STERLINA",   // CORRETTA: EURO
	        "1989", "1990", "1985", "1991",   // CORRETTA: 1989
	        "ANTONIO VIVALDI", "WOLFGANG MOZART", "LUDWIG VAN BEETHOVEN", "JOHANN SEBASTIAN BACH",   // CORRETTA: ANTONIO VIVALDI
	        "SAHARA", "KALAHARI", "GIBSON", "ANTARTICO",   // CORRETTA: SAHARA
	        "SIGMUND FREUD", "CARL JUNG", "ALFRED ADLER", "ERIK ERIKSON",   // CORRETTA: SIGMUND FREUD
	        "BAIKAL", "CRATER", "TANGANYIKA", "SUPERIORE",   // CORRETTA: BAIKAL
	        "1919", "1921", "1918", "1923",   // CORRETTA: 1919
	        "MARK", "STEVE JOBS", "BILL GATES", "LARRY PAGE",   // CORRETTA: BILL GATES
	        "ELEFANTE", "BALENA", "GIRAFFA", "TIGRE",   // CORRETTA: BALAENA
	        "TOTTI", "PELÉ", "MESSI", "RONALDO",   // CORRETTA: PELÉ
	        "PELÉ", "MARADONA", "MESSI", "RONALDO"   // CORRETTA: PELÉ
	    };
		
	private static final String RISPOSTA[] = 
	    {
	        "PARIGI",
	        "1945",
	        "WILLIAM SHAKESPEARE",
	        "GIOVE",
	        "IDROGENO",
	        "8",
	        "GEORGE WASHINGTON",
	        "7",
	        "1945",
	        "DANTE ALIGHIERI",
	        "NILO",
	        "NEIL ARMSTRONG",
	        "1914",
	        "LEONARDO DA VINCI",
	        "PACIFICO",
	        "ALESSANDRO MANZONI",
	        "1957",
	        "MONTE EVEREST",
	        "NICCOLÒ MACHIAVELLI",
	        "EURO",
	        "1989",
	        "ANTONIO VIVALDI",
	        "SAHARA",
	        "SIGMUND FREUD",
	        "BAIKAL",
	        "1919",
	        "BILL GATES",
	        "BALENA",
	        "PELÉ",
	        "PELÉ"
	    };

	
	protected static String getDomande(int i) {
		return DOMANDE[i];
	}
	
	protected static String getRisposte(int i) {
		return RISPOSTE[i];
	}
	
	protected static String getrisposta(int i) {
		return RISPOSTA[i];
	}
}
