package caverna;

class Politica {

	private static final String DOMANDE[] = 
		   {
			"CHE FORMA DI GOVERNO è L'ITALIA?",
			"CHE FORMA DI GOVERNO è LA FRANCIA?",
			"CHE FORMA DI GOVERNO è L'INGHILTERRA?",
			"DOVE SI TROVA IL COMUNISMO?",
			"DOVE SI TROVA IL FASCISMO",
			"CHI VOTA IL CAPO DELLO STATO ITALIANO?",
			"QUANTI SONO I SENATORI IN ITALIA?",
			"QUANTI SONO I DEPUTATI IN ITALIA?",
			"COME SI CHIAMA IL CAPO DELLO STATO IN CARICA NEL 2020?",
			"COME SI CHIAMA IL CAPO DI STATO IN CARICA DAL 2006 AL 2015?"};
	private static final String RISPOSTE[] = 
		   {"REPUBBLICA DEMOCRATICA","REPUBBLICA SEMIPRESIDENZIALE","IMPERO","MONARCHIA",
			"REPUBBLICA DEMOCRATICA","REPUBBLICA SEMIPRESIDENZIALE","IMPERO","MONARCHIA",
			"REPUBBLICA DEMOCRATICA","REPUBBLICA SEMIPRESIDENZIALE","IMPERO","MONARCHIA",
			"DESTRA","SINISTRA","CENTROSX","CENTRODX",
			"DESTRA","SINISTRA","CENTROSX","CENTRODX",
			"IL POPOLO","LE CAMERE","IL PREMIER","NESSUNO",
			"315","200","400","201",
			"315","200","400","201",
			"NAPOLITANO","DE NICOLA","SCALFARO","MATTARELLA",
			"NAPOLITANO","DE NICOLA","SCALFARO","MATTARELLA",};
	private static final String RISPOSTA[] = 
		   {
			"REPUBBLICA DEMOCRATICA",
			"REPUBBLICA SEMIPRESIDENZIALE",
			"MONARCHIA",
			"SINISTRA",
			"DESTRA",
			"LE CAMERE",
			"200",
			"400",
			"MATTARELLA",
			"NAPOLITANO"};
	
	protected static String getDomande(int i) {
		return DOMANDE[i];
	}
	
	protected static String getRisposte(int i) {
		return RISPOSTE[i];
	}
	
	protected static String getrisposta(int i) {
		return RISPOSTA[i];
	}
}
